connection awsiot
address a1wwxdro2bszst-ats.iot.eu-central-1.amazonaws.com:8883

bridge_protocol_version mqttv311

clientid bridgeawsiot
cleansession true
start_type automatic
notifications false
log_type all

bridge_cafile /etc/mosquitto/certs/rootCA.pem
bridge_certfile /etc/mosquitto/certs/cert.crt
bridge_keyfile /etc/mosquitto/certs/private.key

topic localgateway_to_awsiot out 1
topic solarmeter/# out 1
